PythonVersion="3.12.12"
pythonBuildCommandsFile="/home/site/repository/oryx-build-commands.txt"
packagedir=".python_packages/lib/site-packages"
OperationId="6cccd77a408f3f50"
SourceDirectoryInBuildContainer="/tmp/8de1b8a3aa235b1"
PlatformName="python"
CompressDestinationDir="false"
